// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmosauction/cosmosauction/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bfdeb243963206, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bfdeb243963206, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetAuctionBiderRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetAuctionBiderRequest) Reset()         { *m = QueryGetAuctionBiderRequest{} }
func (m *QueryGetAuctionBiderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuctionBiderRequest) ProtoMessage()    {}
func (*QueryGetAuctionBiderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bfdeb243963206, []int{2}
}
func (m *QueryGetAuctionBiderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuctionBiderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuctionBiderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuctionBiderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuctionBiderRequest.Merge(m, src)
}
func (m *QueryGetAuctionBiderRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuctionBiderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuctionBiderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuctionBiderRequest proto.InternalMessageInfo

func (m *QueryGetAuctionBiderRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetAuctionBiderResponse struct {
	AuctionBider AuctionBider `protobuf:"bytes,1,opt,name=auctionBider,proto3" json:"auctionBider"`
}

func (m *QueryGetAuctionBiderResponse) Reset()         { *m = QueryGetAuctionBiderResponse{} }
func (m *QueryGetAuctionBiderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuctionBiderResponse) ProtoMessage()    {}
func (*QueryGetAuctionBiderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bfdeb243963206, []int{3}
}
func (m *QueryGetAuctionBiderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuctionBiderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuctionBiderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuctionBiderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuctionBiderResponse.Merge(m, src)
}
func (m *QueryGetAuctionBiderResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuctionBiderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuctionBiderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuctionBiderResponse proto.InternalMessageInfo

func (m *QueryGetAuctionBiderResponse) GetAuctionBider() AuctionBider {
	if m != nil {
		return m.AuctionBider
	}
	return AuctionBider{}
}

type QueryAllAuctionBiderRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAuctionBiderRequest) Reset()         { *m = QueryAllAuctionBiderRequest{} }
func (m *QueryAllAuctionBiderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAuctionBiderRequest) ProtoMessage()    {}
func (*QueryAllAuctionBiderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bfdeb243963206, []int{4}
}
func (m *QueryAllAuctionBiderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAuctionBiderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAuctionBiderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAuctionBiderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAuctionBiderRequest.Merge(m, src)
}
func (m *QueryAllAuctionBiderRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAuctionBiderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAuctionBiderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAuctionBiderRequest proto.InternalMessageInfo

func (m *QueryAllAuctionBiderRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAuctionBiderResponse struct {
	AuctionBider []AuctionBider      `protobuf:"bytes,1,rep,name=auctionBider,proto3" json:"auctionBider"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAuctionBiderResponse) Reset()         { *m = QueryAllAuctionBiderResponse{} }
func (m *QueryAllAuctionBiderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAuctionBiderResponse) ProtoMessage()    {}
func (*QueryAllAuctionBiderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bfdeb243963206, []int{5}
}
func (m *QueryAllAuctionBiderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAuctionBiderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAuctionBiderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAuctionBiderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAuctionBiderResponse.Merge(m, src)
}
func (m *QueryAllAuctionBiderResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAuctionBiderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAuctionBiderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAuctionBiderResponse proto.InternalMessageInfo

func (m *QueryAllAuctionBiderResponse) GetAuctionBider() []AuctionBider {
	if m != nil {
		return m.AuctionBider
	}
	return nil
}

func (m *QueryAllAuctionBiderResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetAuctionWinnerRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetAuctionWinnerRequest) Reset()         { *m = QueryGetAuctionWinnerRequest{} }
func (m *QueryGetAuctionWinnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuctionWinnerRequest) ProtoMessage()    {}
func (*QueryGetAuctionWinnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bfdeb243963206, []int{6}
}
func (m *QueryGetAuctionWinnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuctionWinnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuctionWinnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuctionWinnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuctionWinnerRequest.Merge(m, src)
}
func (m *QueryGetAuctionWinnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuctionWinnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuctionWinnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuctionWinnerRequest proto.InternalMessageInfo

func (m *QueryGetAuctionWinnerRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetAuctionWinnerResponse struct {
	AuctionWinner AuctionWinner `protobuf:"bytes,1,opt,name=auctionWinner,proto3" json:"auctionWinner"`
}

func (m *QueryGetAuctionWinnerResponse) Reset()         { *m = QueryGetAuctionWinnerResponse{} }
func (m *QueryGetAuctionWinnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAuctionWinnerResponse) ProtoMessage()    {}
func (*QueryGetAuctionWinnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bfdeb243963206, []int{7}
}
func (m *QueryGetAuctionWinnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAuctionWinnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAuctionWinnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAuctionWinnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAuctionWinnerResponse.Merge(m, src)
}
func (m *QueryGetAuctionWinnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAuctionWinnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAuctionWinnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAuctionWinnerResponse proto.InternalMessageInfo

func (m *QueryGetAuctionWinnerResponse) GetAuctionWinner() AuctionWinner {
	if m != nil {
		return m.AuctionWinner
	}
	return AuctionWinner{}
}

type QueryAllAuctionWinnerRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAuctionWinnerRequest) Reset()         { *m = QueryAllAuctionWinnerRequest{} }
func (m *QueryAllAuctionWinnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllAuctionWinnerRequest) ProtoMessage()    {}
func (*QueryAllAuctionWinnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bfdeb243963206, []int{8}
}
func (m *QueryAllAuctionWinnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAuctionWinnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAuctionWinnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAuctionWinnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAuctionWinnerRequest.Merge(m, src)
}
func (m *QueryAllAuctionWinnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAuctionWinnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAuctionWinnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAuctionWinnerRequest proto.InternalMessageInfo

func (m *QueryAllAuctionWinnerRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllAuctionWinnerResponse struct {
	AuctionWinner []AuctionWinner     `protobuf:"bytes,1,rep,name=auctionWinner,proto3" json:"auctionWinner"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllAuctionWinnerResponse) Reset()         { *m = QueryAllAuctionWinnerResponse{} }
func (m *QueryAllAuctionWinnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllAuctionWinnerResponse) ProtoMessage()    {}
func (*QueryAllAuctionWinnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9bfdeb243963206, []int{9}
}
func (m *QueryAllAuctionWinnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllAuctionWinnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllAuctionWinnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllAuctionWinnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllAuctionWinnerResponse.Merge(m, src)
}
func (m *QueryAllAuctionWinnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllAuctionWinnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllAuctionWinnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllAuctionWinnerResponse proto.InternalMessageInfo

func (m *QueryAllAuctionWinnerResponse) GetAuctionWinner() []AuctionWinner {
	if m != nil {
		return m.AuctionWinner
	}
	return nil
}

func (m *QueryAllAuctionWinnerResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "naruto0913.cosmosauction.cosmosauction.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "naruto0913.cosmosauction.cosmosauction.QueryParamsResponse")
	proto.RegisterType((*QueryGetAuctionBiderRequest)(nil), "naruto0913.cosmosauction.cosmosauction.QueryGetAuctionBiderRequest")
	proto.RegisterType((*QueryGetAuctionBiderResponse)(nil), "naruto0913.cosmosauction.cosmosauction.QueryGetAuctionBiderResponse")
	proto.RegisterType((*QueryAllAuctionBiderRequest)(nil), "naruto0913.cosmosauction.cosmosauction.QueryAllAuctionBiderRequest")
	proto.RegisterType((*QueryAllAuctionBiderResponse)(nil), "naruto0913.cosmosauction.cosmosauction.QueryAllAuctionBiderResponse")
	proto.RegisterType((*QueryGetAuctionWinnerRequest)(nil), "naruto0913.cosmosauction.cosmosauction.QueryGetAuctionWinnerRequest")
	proto.RegisterType((*QueryGetAuctionWinnerResponse)(nil), "naruto0913.cosmosauction.cosmosauction.QueryGetAuctionWinnerResponse")
	proto.RegisterType((*QueryAllAuctionWinnerRequest)(nil), "naruto0913.cosmosauction.cosmosauction.QueryAllAuctionWinnerRequest")
	proto.RegisterType((*QueryAllAuctionWinnerResponse)(nil), "naruto0913.cosmosauction.cosmosauction.QueryAllAuctionWinnerResponse")
}

func init() {
	proto.RegisterFile("cosmosauction/cosmosauction/query.proto", fileDescriptor_f9bfdeb243963206)
}

var fileDescriptor_f9bfdeb243963206 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xcf, 0x6e, 0x13, 0x3f,
	0x10, 0xc7, 0xe3, 0xf6, 0xd7, 0xe8, 0x87, 0x69, 0x05, 0x32, 0x39, 0xa0, 0x50, 0x16, 0xe4, 0x43,
	0x5b, 0x21, 0xb1, 0x6e, 0x9a, 0x42, 0x69, 0x91, 0x5a, 0x12, 0xa0, 0xb9, 0x70, 0x28, 0x11, 0x12,
	0x12, 0x07, 0x90, 0x93, 0x9a, 0x65, 0xa5, 0x64, 0xbd, 0xcd, 0x6e, 0xa0, 0x15, 0x82, 0x43, 0x9f,
	0x00, 0x89, 0xb7, 0xe1, 0x05, 0xa8, 0xc4, 0xa5, 0x82, 0x0b, 0x07, 0x84, 0x4a, 0x02, 0xef, 0x81,
	0xd6, 0x9e, 0xd0, 0x35, 0xf9, 0x43, 0xb2, 0xc9, 0xa9, 0xf5, 0xae, 0xe7, 0x3b, 0xdf, 0xcf, 0x8c,
	0x3d, 0x1b, 0xbc, 0x58, 0x95, 0x41, 0x5d, 0x06, 0xbc, 0x59, 0x0d, 0x5d, 0xe9, 0x31, 0x73, 0xb5,
	0xd7, 0x14, 0x8d, 0x03, 0xdb, 0x6f, 0xc8, 0x50, 0x92, 0x05, 0x8f, 0x37, 0x9a, 0xa1, 0x5c, 0x5e,
	0xcf, 0xe5, 0x6d, 0x63, 0x97, 0xb9, 0xca, 0x66, 0x1c, 0xe9, 0x48, 0x15, 0xc2, 0xa2, 0xff, 0x74,
	0x74, 0x76, 0xde, 0x91, 0xd2, 0xa9, 0x09, 0xc6, 0x7d, 0x97, 0x71, 0xcf, 0x93, 0x21, 0x8f, 0x36,
	0x07, 0xf0, 0xf6, 0x9a, 0x96, 0x60, 0x15, 0x1e, 0x08, 0x9d, 0x94, 0xbd, 0xcc, 0x55, 0x44, 0xc8,
	0x73, 0xcc, 0xe7, 0x8e, 0xeb, 0xa9, 0xcd, 0xb0, 0x77, 0x69, 0x90, 0x61, 0x9f, 0x37, 0x78, 0xbd,
	0xa3, 0xca, 0x06, 0xed, 0x84, 0xbf, 0xcf, 0x2a, 0xee, 0xae, 0x68, 0x40, 0xc0, 0xf2, 0x30, 0x01,
	0xaf, 0x5c, 0xcf, 0xeb, 0x44, 0xd0, 0x0c, 0x26, 0x0f, 0x23, 0xbb, 0x3b, 0x2a, 0x6f, 0x59, 0xec,
	0x35, 0x45, 0x10, 0xd2, 0x2a, 0xbe, 0x60, 0x3c, 0x0d, 0x7c, 0xe9, 0x05, 0x82, 0x3c, 0xc0, 0x69,
	0xed, 0xef, 0x22, 0xba, 0x8a, 0x96, 0xce, 0xae, 0xd8, 0xf6, 0x70, 0x25, 0xb5, 0xb5, 0x4e, 0xf1,
	0xbf, 0xa3, 0xef, 0x57, 0x52, 0x65, 0xd0, 0xa0, 0x79, 0x7c, 0x49, 0x25, 0x29, 0x89, 0xb0, 0xa0,
	0xf7, 0x15, 0x23, 0x14, 0xf0, 0x40, 0x32, 0x78, 0xc6, 0xf5, 0x76, 0xc5, 0xbe, 0xca, 0x75, 0xa6,
	0xac, 0x17, 0xf4, 0x2d, 0x9e, 0xef, 0x1d, 0x04, 0x16, 0x9f, 0xe2, 0x59, 0x1e, 0x7b, 0x0e, 0x46,
	0x57, 0x87, 0x35, 0x1a, 0xd7, 0x04, 0xbb, 0x86, 0x1e, 0x15, 0x60, 0xba, 0x50, 0xab, 0xf5, 0x32,
	0xbd, 0x8d, 0xf1, 0x69, 0xbf, 0x21, 0xf9, 0x02, 0xe4, 0xb0, 0xa3, 0xc3, 0x61, 0xeb, 0x13, 0x09,
	0x87, 0xc3, 0xde, 0xe1, 0x8e, 0x80, 0xd8, 0x72, 0x2c, 0x92, 0x7e, 0x44, 0xc0, 0xd9, 0x95, 0xa7,
	0x2f, 0xe7, 0xf4, 0x24, 0x39, 0x49, 0xc9, 0x00, 0x99, 0x52, 0x20, 0x8b, 0xff, 0x04, 0xd1, 0xe6,
	0x0c, 0x92, 0xd5, 0xae, 0x86, 0x3d, 0x56, 0xe7, 0x6f, 0x70, 0x9b, 0x0f, 0x11, 0xbe, 0xdc, 0x27,
	0x0c, 0x0a, 0xc0, 0xf1, 0x1c, 0x8f, 0xbf, 0x80, 0x62, 0xdf, 0x18, 0xb1, 0x02, 0x3a, 0x18, 0x4a,
	0x60, 0x2a, 0xd2, 0xe7, 0x5d, 0x3d, 0x30, 0xad, 0x4f, 0xaa, 0xd9, 0x9f, 0x3a, 0xb0, 0xdd, 0x89,
	0xfa, 0xc3, 0x4e, 0x4f, 0x16, 0x76, 0x62, 0x0d, 0x5f, 0xf9, 0xfc, 0x3f, 0x9e, 0x51, 0x34, 0xe4,
	0x03, 0xc2, 0x69, 0x7d, 0xf3, 0xc9, 0xc6, 0xb0, 0x4e, 0xbb, 0x87, 0x51, 0xf6, 0x76, 0xa2, 0x58,
	0xed, 0x8c, 0xae, 0x1d, 0x7e, 0xf9, 0xf9, 0x7e, 0x2a, 0x47, 0x18, 0x3b, 0x15, 0x81, 0xb9, 0x78,
	0x7d, 0xd0, 0x04, 0x26, 0x3f, 0x10, 0x9e, 0x8d, 0xdf, 0x12, 0x72, 0x77, 0x24, 0x1b, 0xbd, 0x87,
	0x5a, 0xf6, 0xde, 0x78, 0x22, 0x00, 0xb5, 0xad, 0xa0, 0xee, 0x90, 0xcd, 0xa1, 0xa1, 0x8c, 0x8f,
	0x05, 0x7b, 0xad, 0x2e, 0xd9, 0x1b, 0xf2, 0x0d, 0xe1, 0x73, 0xf1, 0x04, 0x85, 0x5a, 0x6d, 0x44,
	0xcc, 0xde, 0x63, 0x70, 0x44, 0xcc, 0x3e, 0x33, 0x8e, 0x6e, 0x2a, 0xcc, 0x5b, 0xe4, 0x66, 0x32,
	0x4c, 0xf2, 0x0b, 0xe1, 0x39, 0xe3, 0xe4, 0x93, 0xa4, 0xe5, 0x37, 0xee, 0x7d, 0xf6, 0xfe, 0x98,
	0x2a, 0x80, 0x57, 0x52, 0x78, 0x05, 0xb2, 0x35, 0x32, 0x9e, 0xfe, 0x82, 0xff, 0x69, 0xe3, 0x09,
	0xc2, 0xe7, 0x8d, 0x14, 0x51, 0x1f, 0x93, 0xb6, 0x60, 0x1c, 0xd4, 0x7e, 0xf3, 0x8b, 0x6e, 0x29,
	0xd4, 0x75, 0xb2, 0x96, 0x10, 0xb5, 0xf8, 0xe8, 0xa8, 0x65, 0xa1, 0xe3, 0x96, 0x85, 0x4e, 0x5a,
	0x16, 0x7a, 0xd7, 0xb6, 0x52, 0xc7, 0x6d, 0x2b, 0xf5, 0xb5, 0x6d, 0xa5, 0x9e, 0x6c, 0x38, 0x6e,
	0xf8, 0xa2, 0x59, 0xb1, 0xab, 0xb2, 0x3e, 0x40, 0x7c, 0xff, 0x2f, 0xf9, 0xf0, 0xc0, 0x17, 0x41,
	0x25, 0xad, 0x7e, 0x03, 0xe5, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x40, 0xfb, 0xf3, 0x43,
	0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a AuctionBider by index.
	AuctionBider(ctx context.Context, in *QueryGetAuctionBiderRequest, opts ...grpc.CallOption) (*QueryGetAuctionBiderResponse, error)
	// Queries a list of AuctionBider items.
	AuctionBiderAll(ctx context.Context, in *QueryAllAuctionBiderRequest, opts ...grpc.CallOption) (*QueryAllAuctionBiderResponse, error)
	// Queries a AuctionWinner by index.
	AuctionWinner(ctx context.Context, in *QueryGetAuctionWinnerRequest, opts ...grpc.CallOption) (*QueryGetAuctionWinnerResponse, error)
	// Queries a list of AuctionWinner items.
	AuctionWinnerAll(ctx context.Context, in *QueryAllAuctionWinnerRequest, opts ...grpc.CallOption) (*QueryAllAuctionWinnerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/naruto0913.cosmosauction.cosmosauction.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuctionBider(ctx context.Context, in *QueryGetAuctionBiderRequest, opts ...grpc.CallOption) (*QueryGetAuctionBiderResponse, error) {
	out := new(QueryGetAuctionBiderResponse)
	err := c.cc.Invoke(ctx, "/naruto0913.cosmosauction.cosmosauction.Query/AuctionBider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuctionBiderAll(ctx context.Context, in *QueryAllAuctionBiderRequest, opts ...grpc.CallOption) (*QueryAllAuctionBiderResponse, error) {
	out := new(QueryAllAuctionBiderResponse)
	err := c.cc.Invoke(ctx, "/naruto0913.cosmosauction.cosmosauction.Query/AuctionBiderAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuctionWinner(ctx context.Context, in *QueryGetAuctionWinnerRequest, opts ...grpc.CallOption) (*QueryGetAuctionWinnerResponse, error) {
	out := new(QueryGetAuctionWinnerResponse)
	err := c.cc.Invoke(ctx, "/naruto0913.cosmosauction.cosmosauction.Query/AuctionWinner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuctionWinnerAll(ctx context.Context, in *QueryAllAuctionWinnerRequest, opts ...grpc.CallOption) (*QueryAllAuctionWinnerResponse, error) {
	out := new(QueryAllAuctionWinnerResponse)
	err := c.cc.Invoke(ctx, "/naruto0913.cosmosauction.cosmosauction.Query/AuctionWinnerAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a AuctionBider by index.
	AuctionBider(context.Context, *QueryGetAuctionBiderRequest) (*QueryGetAuctionBiderResponse, error)
	// Queries a list of AuctionBider items.
	AuctionBiderAll(context.Context, *QueryAllAuctionBiderRequest) (*QueryAllAuctionBiderResponse, error)
	// Queries a AuctionWinner by index.
	AuctionWinner(context.Context, *QueryGetAuctionWinnerRequest) (*QueryGetAuctionWinnerResponse, error)
	// Queries a list of AuctionWinner items.
	AuctionWinnerAll(context.Context, *QueryAllAuctionWinnerRequest) (*QueryAllAuctionWinnerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AuctionBider(ctx context.Context, req *QueryGetAuctionBiderRequest) (*QueryGetAuctionBiderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuctionBider not implemented")
}
func (*UnimplementedQueryServer) AuctionBiderAll(ctx context.Context, req *QueryAllAuctionBiderRequest) (*QueryAllAuctionBiderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuctionBiderAll not implemented")
}
func (*UnimplementedQueryServer) AuctionWinner(ctx context.Context, req *QueryGetAuctionWinnerRequest) (*QueryGetAuctionWinnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuctionWinner not implemented")
}
func (*UnimplementedQueryServer) AuctionWinnerAll(ctx context.Context, req *QueryAllAuctionWinnerRequest) (*QueryAllAuctionWinnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuctionWinnerAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naruto0913.cosmosauction.cosmosauction.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuctionBider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAuctionBiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuctionBider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naruto0913.cosmosauction.cosmosauction.Query/AuctionBider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuctionBider(ctx, req.(*QueryGetAuctionBiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuctionBiderAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAuctionBiderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuctionBiderAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naruto0913.cosmosauction.cosmosauction.Query/AuctionBiderAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuctionBiderAll(ctx, req.(*QueryAllAuctionBiderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuctionWinner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAuctionWinnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuctionWinner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naruto0913.cosmosauction.cosmosauction.Query/AuctionWinner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuctionWinner(ctx, req.(*QueryGetAuctionWinnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuctionWinnerAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAuctionWinnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuctionWinnerAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/naruto0913.cosmosauction.cosmosauction.Query/AuctionWinnerAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuctionWinnerAll(ctx, req.(*QueryAllAuctionWinnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "naruto0913.cosmosauction.cosmosauction.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AuctionBider",
			Handler:    _Query_AuctionBider_Handler,
		},
		{
			MethodName: "AuctionBiderAll",
			Handler:    _Query_AuctionBiderAll_Handler,
		},
		{
			MethodName: "AuctionWinner",
			Handler:    _Query_AuctionWinner_Handler,
		},
		{
			MethodName: "AuctionWinnerAll",
			Handler:    _Query_AuctionWinnerAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmosauction/cosmosauction/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetAuctionBiderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuctionBiderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuctionBiderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAuctionBiderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuctionBiderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuctionBiderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AuctionBider.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllAuctionBiderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAuctionBiderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAuctionBiderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAuctionBiderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAuctionBiderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAuctionBiderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuctionBider) > 0 {
		for iNdEx := len(m.AuctionBider) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AuctionBider[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAuctionWinnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuctionWinnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuctionWinnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAuctionWinnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAuctionWinnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAuctionWinnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.AuctionWinner.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllAuctionWinnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAuctionWinnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAuctionWinnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllAuctionWinnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllAuctionWinnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllAuctionWinnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuctionWinner) > 0 {
		for iNdEx := len(m.AuctionWinner) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AuctionWinner[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetAuctionBiderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAuctionBiderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AuctionBider.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllAuctionBiderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAuctionBiderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AuctionBider) > 0 {
		for _, e := range m.AuctionBider {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAuctionWinnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAuctionWinnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AuctionWinner.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllAuctionWinnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllAuctionWinnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AuctionWinner) > 0 {
		for _, e := range m.AuctionWinner {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAuctionBiderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuctionBiderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuctionBiderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAuctionBiderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuctionBiderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuctionBiderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionBider", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AuctionBider.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAuctionBiderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAuctionBiderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAuctionBiderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAuctionBiderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAuctionBiderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAuctionBiderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionBider", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionBider = append(m.AuctionBider, AuctionBider{})
			if err := m.AuctionBider[len(m.AuctionBider)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAuctionWinnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuctionWinnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuctionWinnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAuctionWinnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAuctionWinnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAuctionWinnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionWinner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AuctionWinner.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAuctionWinnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAuctionWinnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAuctionWinnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllAuctionWinnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllAuctionWinnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllAuctionWinnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionWinner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionWinner = append(m.AuctionWinner, AuctionWinner{})
			if err := m.AuctionWinner[len(m.AuctionWinner)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
